# Generated by Django 5.1.4 on 2025-01-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifestos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifesto',
            name='crime',
            field=models.CharField(default='Null', max_length=3000),
        ),
        migrations.AddField(
            model_name='manifesto',
            name='economy',
            field=models.CharField(default='Null', max_length=3000),
        ),
        migrations.AddField(
            model_name='manifesto',
            name='education',
            field=models.CharField(default='Null', max_length=3000),
        ),
        migrations.AddField(
            model_name='manifesto',
            name='environment',
            field=models.CharField(default='Null', max_length=3000),
        ),
        migrations.AddField(
            model_name='manifesto',
            name='health',
            field=models.CharField(default='Null', max_length=3000),
        ),
        migrations.AddField(
            model_name='manifesto',
            name='housing',
            field=models.CharField(default='Null', max_length=3000),
        ),
        migrations.AddField(
            model_name='manifesto',
            name='immigration',
            field=models.CharField(default='Null', max_length=3000),
        ),
        migrations.AddField(
            model_name='manifesto',
            name='transport',
            field=models.CharField(default='Null', max_length=3000),
        ),
        migrations.AlterField(
            model_name='manifesto',
            name='name',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AlterField(
            model_name='manifesto',
            name='summary',
            field=models.CharField(default='Null', max_length=3000),
        ),
    ]
